# Generated by Django 6.0 on 2026-03-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('curriculum', models.CharField(choices=[('CBC', 'CBC (Grade 10-12)'), ('844', '8-4-4 (Form 3-4)')], default='CBC', max_length=5)),
                ('current_class', models.CharField(choices=[('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12'), ('Form 3', 'Form 3'), ('Form 4', 'Form 4')], max_length=20)),
                ('cbc_pathway', models.CharField(blank=True, choices=[('STEM', 'STEM (Science, Tech, Engineering, Math)'), ('ARTS', 'Arts and Sports Science'), ('SOCIAL', 'Social Sciences')], max_length=50, null=True)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_phone', models.CharField(max_length=15)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('admission_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
