# Generated by Django 6.0.4 on 2026-05-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cbc_pathway',
        ),
    ]
