# Generated by Django 6.0.4 on 2026-05-23 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_cbcpathway_subject_is_core_subject_pathway'),
        ('students', '0002_remove_student_cbc_pathway'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cbc_pathway',
            field=models.ForeignKey(blank=True, help_text='Only needed for Grade 10-12 students', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.cbcpathway'),
        ),
    ]
