# Generated by Django 6.0 on 2026-03-10 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('message_body', models.TextField()),
                ('purpose', models.CharField(choices=[('GENERAL', 'General Announcement'), ('FEES', 'Fee Reminder'), ('ACADEMIC', 'Academic Report'), ('EMERGENCY', 'Emergency Alert')], default='GENERAL', max_length=20)),
                ('status', models.CharField(default='Sent', max_length=10)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(help_text='Student whose parent received the SMS', on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
