# Generated by Django 6.0.4 on 2026-05-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_systemlicense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kcsemarksrecord',
            old_name='cat_marks',
            new_name='cat_1',
        ),
        migrations.RenameField(
            model_name='kcsemarksrecord',
            old_name='exam_marks',
            new_name='cat_2',
        ),
        migrations.AddField(
            model_name='kcsemarksrecord',
            name='exam',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
