# Generated by Django 6.0.4 on 2026-05-23 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_rename_cat_marks_kcsemarksrecord_cat_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBCPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., STEM, Social Sciences, Arts & Sports', max_length=100)),
                ('code', models.CharField(help_text='e.g., STEM, SS, ARTS', max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='is_core',
            field=models.BooleanField(default=True, help_text='Is this subject compulsory for all students?'),
        ),
        migrations.AddField(
            model_name='subject',
            name='pathway',
            field=models.ForeignKey(blank=True, help_text='Leave blank if it is a Core subject', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.cbcpathway'),
        ),
    ]
