# Generated by Django 6.0.4 on 2026-05-23 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_cbcpathway_subject_is_core_subject_pathway'),
        ('students', '0003_student_cbc_pathway'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kcsemarksrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='kcsemarksrecord',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
        migrations.AlterUniqueTogether(
            name='kcsemarksrecord',
            unique_together={('student', 'subject', 'term', 'academic_year')},
        ),
    ]
