# Generated by Django 6.0.4 on 2026-05-24 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studymaterial',
            old_name='video_url',
            new_name='video_link',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='resource_type',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='target_class',
            field=models.CharField(max_length=50),
        ),
    ]
